In [9]:
import seaborn as sns
import pandas as pd
import numpy as np

In [10]:
df=sns.load_dataset('iris')

In [11]:
df.head()

   sepal_length  sepal_width  petal_length  petal_width species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa

In [12]:
df['species'].unique()

array(['setosa', 'versicolor', 'virginica'], dtype=object)

In [13]:
df.isnull().sum()

sepal_length    0
sepal_width     0
petal_length    0
petal_width     0
species         0
dtype: int64

In [14]:
df['species']!='setosa'

0      False
1      False
2      False
3      False
4      False
       ...
145     True
146     True
147     True
148     True
149     True
Name: species, Length: 150, dtype: bool

In [15]:
df=df[df['species']!='setosa']

In [16]:
df.head()

    sepal_length  sepal_width  petal_length  petal_width     species
50           7.0          3.2           4.7          1.4  versicolor
51           6.4          3.2           4.5          1.5  versicolor
52           6.9          3.1           4.9          1.5  versicolor
53           5.5          2.3           4.0          1.3  versicolor
54           6.5          2.8           4.6          1.5  versicolor

In [17]:
df['species']=df['species'].map({'versicolor':0,'virginica':1})

In [18]:
df.head()

    sepal_length  sepal_width  petal_length  petal_width  species
50           7.0          3.2           4.7          1.4        0
51           6.4          3.2           4.5          1.5        0
52           6.9          3.1           4.9          1.5        0
53           5.5          2.3           4.0          1.3        0
54           6.5          2.8           4.6          1.5        0

In [19]:
### split dataset into independent and dependent features
X=df.iloc[:,-1]
y=df.iloc[:,-1]

In [20]:
X

50     0
51     0
52     0
53     0
54     0
      ..
145    1
146    1
147    1
148    1
149    1
Name: species, Length: 100, dtype: int64

In [22]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(
    X,y,test_size=0.25,random_state=42
)

In [23]:
X_train

65     0
90     0
146    1
59     0
122    1
      ..
110    1
121    1
64     0
142    1
101    1
Name: species, Length: 75, dtype: int64

In [24]:
 y_train

65     0
90     0
146    1
59     0
122    1
      ..
110    1
121    1
64     0
142    1
101    1
Name: species, Length: 75, dtype: int64

In [1]:
from sklearn.linear_model import LogisticRegression
classifier=LogisticRegression()

In [29]:
from sklearn.model_selection import GridSearchCV
parameter={'penalty':['l1','l2','elasticnet'],'C':[1,2,3,4,50,60,70,80,]}

In [30]:
classifier_regressor = GridSearchCV(
    estimator=classifier,
    param_grid=parameter,
    scoring='accuracy',
    cv=5
)

In [32]:
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import GridSearchCV

classifier = LogisticRegression()

parameter = {
    'penalty': ['l1', 'l2'],
    'C': [1, 2, 3, 5, 10],
    'solver': ['liblinear']
}

classifier_regressor = GridSearchCV(
    classifier,
    param_grid=parameter,
    scoring='accuracy',
    cv=5
)

# Make X_train 2D if needed
X_train = X_train.to_frame()

classifier_regressor.fit(X_train, y_train)

GridSearchCV(cv=5, estimator=LogisticRegression(),
             param_grid={'C': [1, 2, 3, 5, 10], 'penalty': ['l1', 'l2'],
                         'solver': ['liblinear']},
             scoring='accuracy')

In [33]:
print(classifier_regressor.best_params_)

{'C': 1, 'penalty': 'l1', 'solver': 'liblinear'}

In [34]:
print(classifier_regressor.best_score_)

1.0

In [35]:
y_pred=classifier_regressor.predict(X_train)

In [36]:
y_pred

array([0, 0, 1, 0, 1, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1,
       0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1,
       1, 1, 0, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 1,
       1, 1, 1, 0, 1, 1, 0, 1, 1])

In [37]:
from sklearn.metrics import accuracy_score,classification_report

In [39]:
score=accuracy_score(y_pred,y_test)
print(score)

ValueError: Found input variables with inconsistent numbers of samples: [75, 25]